language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8

env:
  global:
    - MONGODB_VERSION=3.2.2

script: sbt ++$TRAVIS_SCALA_VERSION test

services:
  - mongodb

before_script:
  - sh travisMongoUserAdd.sh