language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8

script: sbt ++$TRAVIS_SCALA_VERSION test

services:
  - mongodb

before_script:
  - sleep 15
  - mongo test --eval 'db.createUser({user:"root4", pwd:"flo",roles:[{ role: "readWrite", db: "test" }]});'